import { MenuItem, ClassicSpotlight } from './types';

export const STORE_INFO = {
  name: 'Cairo Cravings',
  tagline: "Tampa's First Authentic Egyptian Street Food",
  address: '11009 N 56th St, Temple Terrace, FL 33617',
  area: 'Near USF Tampa Campus',
  phone: '(813) 876-7178',
  phoneRaw: 'tel:8138767178',
  email: 'info@cairocravings.com',
  instagram: '@cairo_cravings',
  instagramUrl: 'https://instagram.com/cairo_cravings',
  hours: [
    { days: 'Monday – Thursday', time: '11:00 AM – 10:00 PM' },
    { days: 'Friday – Saturday', time: '11:00 AM – Midnight (Late Night Street Food)' },
    { days: 'Sunday', time: '12:00 PM – 9:00 PM' },
  ],
  googleMapsUrl: 'https://maps.google.com/?q=11009+N+56th+St,+Temple+Terrace,+FL+33617',
  embedMapSrc: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3521.905642875153!2d-82.39343362453664!3d28.026027975999824!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x88c2c7ae0a3f8f17%3A0xb3280c44c9b9cb1a!2s11009%20N%2056th%20St%2C%20Temple%20Terrace%2C%20FL%2033617!5e0!3m2!1sen!2sus!4v1710000000000!5m2!1sen!2sus',
};

export const CLASSICS_SPOTLIGHT: ClassicSpotlight[] = [
  {
    id: 'koshary',
    title: 'THE KOSHARY BOWL',
    subtitle: 'كشري مصري أصيل',
    tagline: 'Egypt’s Iconic National Street Champion',
    shortDesc: 'Signature Egyptian bowl, layered rice, macaroni, brown lentils & chickpeas topped with rich salsa and crispy onions.',
    fullDesc: 'The undisputed king of Egyptian street food. Fluffy Egyptian short-grain rice, vermicelli, tender ditalini macaroni, and earthy brown lentils layered with nutty chickpeas. Drenched in our slow-simmered spiced cumin-garlic tomato salsa, finished with tangy garlic-vinegar Da’a, and crowned with a generous mountain of crispy, golden caramelized onions (Ward). Add our fiery Shatta chili sauce to taste.',
    price: '$11.99',
    badge: 'National Dish #1',
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=800&q=80',
    spiceLevel: 2,
    dietary: ['100% Vegan', 'High Fiber', 'Cairo Street Classic'],
    keyIngredients: ['Egyptian Rice & Vermicelli', 'Brown Lentils', 'Macaroni', 'Chickpeas', 'Crispy Golden Onions', 'Garlic Tomato Salsa', 'Da’a Cumin Dressing'],
  },
  {
    id: 'hawawshi',
    title: 'HAWAWSHI FLATBREAD',
    subtitle: 'حواوشي بلدي بالسمنة',
    tagline: 'Cairo Stone-Baked Spiced Meat Pocket',
    shortDesc: 'Hawawshi flatbread with spiced Egyptian minced beef & lamb baked in stone oven till crispy-golden.',
    fullDesc: 'Egypt’s legendary street sandwich. Prime ground beef and succulent lamb seasoned with grated onions, sweet bell peppers, hot green chilis, fresh parsley, and our signature 7-spice Nile blend. Stuffed into fresh, doughy Egyptian Baladi bread and stone-baked until the outside turns blistering-crisp while the savory interior stays richly spiced and juicy.',
    price: '$13.49',
    badge: 'Stone-Oven Baked',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=800&q=80',
    spiceLevel: 2,
    dietary: ['100% Halal', 'Chef Favorite', 'Baked Fresh to Order'],
    keyIngredients: ['Prime Halal Beef & Lamb', 'Fresh Egyptian Baladi Bread', 'Sweet & Hot Peppers', 'Cairo 7-Spice Blend', 'Fresh Garlic & Parsley'],
  },
  {
    id: 'taameya',
    title: "TA'AMEYA FALAFEL BOWL",
    subtitle: 'طعمية إسكندراني بالسمسم',
    tagline: 'The Original Green Egyptian Falafel',
    shortDesc: "Ta'ameya falafel bowl, crisp fava bean patties with toasted sesame, tahina drizzle, and fresh baladi salad.",
    fullDesc: 'Egyptians invented falafel, and Ta’ameya is the authentic original. Unlike chickpea falafel found elsewhere, true Egyptian Ta’ameya is crafted from split dried fava beans whipped with fresh garden dill, cilantro, leeks, and roasted garlic. Rolled in toasted sesame seeds and fried to an extraordinary golden crunch with a fluffy, vibrant-green herbal interior.',
    price: '$10.99',
    badge: 'Ancient Recipe',
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=800&q=80',
    spiceLevel: 1,
    dietary: ['100% Vegan', 'Gluten-Free Friendly', 'Fava Bean Protein'],
    keyIngredients: ['Egyptian Fava Beans (Ful)', 'Fresh Dill & Cilantro', 'Leeks & Garlic', 'Golden Sesame Seeds', 'House Sesame Tahina'],
  },
  {
    id: 'shawarma',
    title: 'EGYPTIAN SHAWARMA',
    subtitle: 'شاورما على الطريقة المصرية',
    tagline: 'Flat-Top Sizzled with Tomato & Parsley',
    shortDesc: 'Tender marinated beef or chicken, flash-seared with tomatoes, fresh parsley & creamy garlic tomeya.',
    fullDesc: 'Unlike Levant shawarma, traditional Egyptian street shawarma is thinly carved, then sizzled on a blazing flat-top skillet with sweet diced tomatoes, fresh Italian parsley, and sumac-tossed red onions. Wrapped in warm, fluffy Egyptian Fino bread or Baladi pocket with a thick drizzle of house-whipped garlic Tomeya and roasted sesame tahini.',
    price: '$12.99',
    badge: 'Sizzling Grill',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=800&q=80',
    spiceLevel: 1,
    dietary: ['100% Halal', 'High Protein', 'Pickled Turnip Garnish'],
    keyIngredients: ['Marinated Beef or Chicken', 'Griddled Roma Tomatoes', 'Sumac Red Onions', 'Whipped Garlic Tomeya', 'Toasted Egyptian Fino Bread'],
  },
];

export const MENU_ITEMS: MenuItem[] = [
  // Signature Bowls & Koshary
  {
    id: 'bowl-koshary-classic',
    name: 'Classic Cairo Koshary',
    arabicName: 'كشري القاهرة الكلاسيكي',
    category: 'bowls',
    description: 'The national dish: rice, macaroni, brown lentils, chickpeas, spicy garlic salsa, da’a vinegar dressing, and caramelized onions.',
    price: '$11.99',
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegan: true,
    isSignature: true,
    ingredients: ['Rice', 'Lentils', 'Macaroni', 'Chickpeas', 'Garlic Tomato Sauce', 'Da’a Cumin Dressing', 'Crispy Onions'],
    pairing: 'Iced Karkadeh Hibiscus Tea',
  },
  {
    id: 'bowl-koshary-royal',
    name: 'Royal Hawawshi Koshary Bowl',
    arabicName: 'كشري ملكي بقطع الحواوشي',
    category: 'bowls',
    description: 'Our classic Koshary bowl elevated with mini bites of seasoned halal beef Hawawshi, extra crispy fried onions, and melted mozzarella drizzle.',
    price: '$15.99',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isHalal: true,
    isSignature: true,
    ingredients: ['Classic Koshary Base', 'Spiced Halal Beef Bites', 'Crispy Golden Onions', 'Mozzarella Drizzle', 'Extra Salsa'],
    pairing: 'Egyptian Mint Tea',
  },
  {
    id: 'bowl-taameya-harvest',
    name: "Nile Green Ta'ameya Bowl",
    arabicName: 'طبق الطعمية بالخضار والطحينة',
    category: 'bowls',
    description: 'Four hot sesame fava bean falafels served over spiced yellow basmati rice, Egyptian salata baladi, creamy hummus, pickled turnips, and sesame tahina.',
    price: '$12.49',
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegan: true,
    ingredients: ['4x Sesame Ta’ameya', 'Spiced Basmati Rice', 'Egyptian Baladi Salad', 'Silky Hummus', 'Pickled Turnips', 'Sesame Tahina'],
    pairing: 'Fresh Lime-Mint Soda',
  },
  {
    id: 'bowl-shawarma-street',
    name: 'Downtown Cairo Shawarma Bowl',
    arabicName: 'طبق شاورما بلدي مع الرز البسمتي',
    category: 'bowls',
    description: 'Sizzling spiced chicken or halal beef shawarma griddled with tomatoes & sumac onions, served over fragrant turmeric rice with garlic tomeya whip.',
    price: '$14.99',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isHalal: true,
    ingredients: ['Halal Shawarma Meat', 'Fragrant Turmeric Rice', 'Garlic Tomeya', 'Sumac Parsley Onions', 'Pickled Wild Cucumbers'],
    pairing: 'Egyptian Mint Tea',
  },

  // Street Sandwiches
  {
    id: 'sand-hawawshi-classic',
    name: 'Classic Cairo Hawawshi',
    arabicName: 'حواوشي بلدي أصلي',
    category: 'sandwiches',
    description: 'Stone-baked Egyptian flatbread packed with spiced ground beef, onions, and Cairo herbs until toasted and crisp on the edges.',
    price: '$13.49',
    image: 'https://images.unsplash.com/photo-1565299585323-38d6b0865b47?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isHalal: true,
    isSignature: true,
    ingredients: ['Egyptian Baladi Dough', 'Halal Ground Beef', 'Cairo 7-Spices', 'Green Chili', 'Garlic'],
    pairing: 'Pickled Eggplant & Tahina',
  },
  {
    id: 'sand-hawawshi-cheese',
    name: 'Alexandrian Cheesy Hawawshi',
    arabicName: 'حواوشي إسكندراني بالجبنة الرومي',
    category: 'sandwiches',
    description: 'Our spiced beef hawawshi stuffed with melted Egyptian Roumy and mozzarella cheese with sliced jalapeño peppers for an epic cheese pull.',
    price: '$14.99',
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 3,
    isHalal: true,
    ingredients: ['Spiced Halal Beef', 'Melted Roumy Cheese', 'Mozzarella', 'Spicy Green Pepper', 'Crispy Flatbread'],
    pairing: 'Cold Karkadeh',
  },
  {
    id: 'sand-shawarma-beef',
    name: 'Tahrir Beef Shawarma Fino',
    arabicName: 'سندوتش شاورما لحمة بالعيش الفينو',
    category: 'sandwiches',
    description: 'Thinly carved marinated beef seared on iron with roasted tomatoes and parsley, tucked into soft Egyptian fino bread with rich sesame tahini.',
    price: '$12.99',
    image: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isHalal: true,
    ingredients: ['Marinated Beef', 'Egyptian Fino Bread', 'Roasted Tomatoes', 'Parsley Sumac Slaw', 'Tahina Sauce'],
    pairing: 'Salata Baladi',
  },
  {
    id: 'sand-taameya-pocket',
    name: 'Traditional Baladi Ta’ameya Pocket',
    arabicName: 'سندوتش طعمية سخنة بالعيش البلدي',
    category: 'sandwiches',
    description: 'Piping hot sesame fava falafel smashed inside a warm baladi pita pocket with Egyptian chopped salad, fried eggplant slices, and garlic tahini.',
    price: '$8.99',
    image: 'https://images.unsplash.com/photo-1593560708920-61dd98c46a4e?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 1,
    isVegan: true,
    ingredients: ['Egyptian Baladi Bread', 'Golden Ta’ameya', 'Fried Eggplant', 'Tomato Cucumber Salad', 'Garlic Tahini'],
    pairing: 'Egyptian Mint Tea',
  },
  {
    id: 'sand-kebda-eskandarani',
    name: 'Alexandrian Kebda (Spiced Beef)',
    arabicName: 'كبدة إسكندراني بالثوم والفلفل الحار',
    category: 'sandwiches',
    description: 'Sautéed tender beef strips seasoned with crushed garlic, cumin, coriander, and fiery green peppers finished with fresh Egyptian lime juice.',
    price: '$12.49',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 3,
    isHalal: true,
    ingredients: ['Tender Halal Beef', 'Crushed Garlic & Cumin', 'Fiery Green Peppers', 'Fresh Lime Juice', 'Warm Fino Bread'],
    pairing: 'Iced Karkadeh',
  },

  // Appetizers & Sides
  {
    id: 'side-baba-ghanoush',
    name: 'Charred Nile Baba Ghanoush',
    arabicName: 'بابا غنوج مشوي مدخن',
    category: 'sides',
    description: 'Open-fire charred eggplant whipped with sesame tahina, lemon juice, roasted garlic, and cold-pressed extra virgin olive oil with pomegranate pearls.',
    price: '$6.99',
    image: 'https://images.unsplash.com/photo-1577906096429-f73c2c312435?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegan: true,
    ingredients: ['Smoked Eggplant', 'Sesame Tahini', 'Extra Virgin Olive Oil', 'Garlic', 'Warm Baladi Pita'],
  },
  {
    id: 'side-egyptian-hummus',
    name: 'Smooth Egyptian Hummus',
    arabicName: 'حمص بطحينة وزيت الزيتون البكر',
    category: 'sides',
    description: 'Ultra-creamy chickpea puree with toasted Egyptian cumin, fresh garlic, lemon, and rich olive oil pool, served with hot baladi bread.',
    price: '$6.49',
    image: 'https://images.unsplash.com/photo-1541518763669-27fef04b14ea?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegan: true,
    ingredients: ['Chickpeas', 'Tahini', 'Toasted Cumin', 'Olive Oil', 'Baladi Bread'],
  },
  {
    id: 'side-pickled-eggplant',
    name: 'Betingan Mekhalel (Spiced Pickled Eggplant)',
    arabicName: 'باذنجان مخلل بالدقة والثوم والخل',
    category: 'sides',
    description: 'Tender baby eggplants stuffed with a zesty marinade of crushed garlic, red chili peppers, cumin, vinegar, and fresh lemon. Street food staple!',
    price: '$5.99',
    image: 'https://images.unsplash.com/photo-1528735602780-2552fd46c7af?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 2,
    isVegan: true,
    ingredients: ['Baby Eggplants', 'Red Chili Paste', 'Garlic', 'Cumin & Coriander', 'White Vinegar & Lime'],
  },
  {
    id: 'side-salata-baladi',
    name: 'Salata Baladi (Nile Street Salad)',
    arabicName: 'سلطة بلدي بالكمون والليمون',
    category: 'sides',
    description: 'Crunchy diced Persian cucumbers, vine-ripened tomatoes, red onion, fresh dill, mint, and parsley tossed in cumin-lemon olive oil dressing.',
    price: '$5.49',
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegan: true,
    ingredients: ['Persian Cucumbers', 'Vine Tomatoes', 'Fresh Dill & Mint', 'Red Onion', 'Cumin Lemon Dressing'],
  },
  {
    id: 'side-baladi-bread',
    name: 'Hot Egyptian Baladi Bread (3 Pcs)',
    arabicName: 'عيش بلدي سخن بالردة',
    category: 'sides',
    description: 'Freshly baked Egyptian whole wheat flatbread coated in toasted wheat bran (Radda), baked at high heat for signature puff pockets.',
    price: '$3.99',
    image: 'https://images.unsplash.com/photo-1509722747041-616f39b57569?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegan: true,
    ingredients: ['Stone-Ground Whole Wheat', 'Natural Wheat Bran (Radda)', 'Yeast', 'Sea Salt'],
  },
  {
    id: 'side-extra-onions',
    name: 'Golden Crispy Onions Basket (Ward)',
    arabicName: 'ورد بصل مقرمش ذهبي',
    category: 'sides',
    description: 'The crowning glory of Koshary. Thinly shaved sweet onions fried to deep golden, shattering crisp perfection with a hint of cumin.',
    price: '$3.49',
    image: 'https://images.unsplash.com/photo-1589302168068-964664d93dc0?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegan: true,
    ingredients: ['Sweet Yellow Onions', 'Crispy Flour Crust', 'Cumin Seasoning'],
  },

  // Desserts & Teas
  {
    id: 'dessert-om-ali',
    name: 'Om Ali (Royal Egyptian Bread Pudding)',
    arabicName: 'أم علي الملكية بالمكسرات والقشطة',
    category: 'desserts',
    description: 'Egypt’s most beloved dessert: flaky puff pastry layers soaked in sweet vanilla milk, topped with toasted almonds, pistachios, raisins, and heavy clotted cream, broiled golden.',
    price: '$7.99',
    image: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    isSignature: true,
    ingredients: ['Flaky Pastry', 'Whole Sweetened Milk', 'Heavy Cream (Eshta)', 'Roasted Pistachios & Almonds', 'Golden Raisins'],
  },
  {
    id: 'dessert-baklava',
    name: 'Cairo Pistachio Baklava Rolls',
    arabicName: 'بقلاوة مصرية بالفستق الحلبي',
    category: 'desserts',
    description: 'Crisp, micro-thin phyllo pastry rolls packed with finely crushed Turkish pistachios, soaked in orange blossom honey syrup.',
    price: '$6.49',
    image: 'https://images.unsplash.com/photo-1519869325930-281384150729?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    ingredients: ['Phyllo Dough', 'Crushed Pistachios', 'Pure Ghee', 'Orange Blossom Syrup'],
  },
  {
    id: 'dessert-basbousa',
    name: 'Rosewater Basbousa with Eshta',
    arabicName: 'بسبوسة بالسمن البلدي والقشطة',
    category: 'desserts',
    description: 'Golden semolina diamond cake infused with clarified butter, bathed in fragrant rosewater syrup, served with a cloud of fresh Egyptian clotted cream.',
    price: '$6.99',
    image: 'https://images.unsplash.com/photo-1587314168485-3236d6710814?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegetarian: true,
    ingredients: ['Coarse Semolina', 'Pure Ghee', 'Rosewater & Lemon Syrup', 'Fresh Eshta Cream', 'Toasted Almond'],
  },
  {
    id: 'drink-mint-tea',
    name: 'Authentic Egyptian Mint Tea',
    arabicName: 'شاي مصري بالنعناع البلدي الفريش',
    category: 'desserts',
    description: 'Strong steeped black Ceylon tea infused with bruised fresh garden mint leaves and pure cane sugar, served piping hot in traditional glassware.',
    price: '$3.99',
    image: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegan: true,
    ingredients: ['Black Ceylon Tea', 'Fresh Garden Spearmint', 'Pure Cane Sugar', 'Boiling Spring Water'],
  },
  {
    id: 'drink-karkadeh',
    name: 'Iced Nile Karkadeh (Hibiscus Tea)',
    arabicName: 'كركديه مصري مثلج ومنعش',
    category: 'desserts',
    description: 'Egypt’s legendary deep-ruby welcome drink. Brewed from dried Nile hibiscus sabdariffa flowers, naturally sweet-tart and chilled over crushed ice.',
    price: '$4.49',
    image: 'https://images.unsplash.com/photo-1556679343-c7306c1976bc?auto=format&fit=crop&w=600&q=80',
    spiceLevel: 0,
    isVegan: true,
    isSignature: true,
    ingredients: ['Upper Egypt Hibiscus Petals', 'Pure Cane Sugar', 'Ice', 'Touch of Rosewater'],
  },
];
